language: node_js
sudo: required
node_js:
  - 6
services: 
  - docker
cache:
  directories:
    - node_modules
env:
  global:
    - IMAGE_NAME=cloudchaos/fullstack-example
    - version=0.0.2
    - MONGODB_HOST=mongodb
    - MONGODB_PORT=27017

before_install:
  - docker run --name mongodb -d mongo
  - docker build --tag ${IMAGE_NAME} ./
  - docker images

install:
  - docker run --name movie-api --link ${MONGODB_HOST}:${MONGODB_PORT} -e "MONGODB_HOST=${MONGODB_HOST}" -e "MONGODB_PORT=${MONGODB_PORT}" -p 3000:3000 -d ${IMAGE_NAME}
  - docker ps
  - npm install

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master